#---------Joins

#31. Display the customer name and their order details.
select c.customer_name,o.* from customer_details c inner join order_details o 
on c.customer_id=o.customer_id;

#32. Display customer name, product name, quantity, and order date.
select c.customer_name,p.product_name,o.quantity,o.order_date 
from customer_details c inner join order_details o inner join product_details p
on c.customer_id=o.customer_id and p.product_id=o.product_id;

#33. Display customer name and product name for every order.
select c.customer_name,p.product_name 
from customer_details c inner join order_details o inner join product_details p
on c.customer_id=o.customer_id and p.product_id=o.product_id;

#34. Find all orders placed by customers from Kochi.
select o.*
from customer_details c inner join order_details o 
on c.customer_id=o.customer_id where city="Kochi";

#35. Display the customer name, product name, category, quantity, and price for every order.
select c.customer_name,p.product_name,p.category,o.quantity,p.price
from customer_details c inner join order_details o inner join product_details p
on c.customer_id=o.customer_id and p.product_id=o.product_id;

#36. Find how many orders each customer has placed.
select c.customer_name,count(o.quantity) no_of_order
from customer_details c inner join order_details o 
on c.customer_id=o.customer_id group by c.customer_id,c.customer_name;

#37. Find the total quantity purchased by each customer.
select c.customer_name,sum(o.quantity) total_quantity
from customer_details c inner join order_details o 
on c.customer_id=o.customer_id group by c.customer_id,c.customer_name;

#38. Find the total quantity sold for each product.
select p.product_id,p.product_name,sum(o.quantity) total_quantity
from product_details p left join order_details o 
on p.product_id=o.product_id group by p.product_id,p.product_name;

#39. Find the customers who purchased Electronics products.
select c.customer_name
from customer_details c  inner join order_details o inner join product_details p
on c.customer_id=o.customer_id and p.product_id=o.product_id where p.category="Electronics";

#40. Find the products purchased by the customer named Rahul.
select p.product_name
from customer_details c  inner join order_details o inner join product_details p
on c.customer_id=o.customer_id and p.product_id=o.product_id where c.customer_name="Rahul";

#41. -- Calculate the total amount for each order using:
-- price × quantity,Display:order ID,product name,quantity,price total amount
select o.order_id,p.product_name,o.quantity,p.price,p.price*o.quantity as total_amount
from order_details o inner join product_details p
on  p.product_id=o.product_id ;

#42. Find the total sales amount.
select sum(p.price*o.quantity) as total_sales_amount
from order_details o inner join product_details p
on  p.product_id=o.product_id ;

#43. Find the total sales amount generated by each product.
select p.product_id,p.product_name,sum(p.price*o.quantity) as total_sales_amount
from order_details o inner join product_details p
on  p.product_id=o.product_id group by p.product_id,p.product_name;

#44. Find the total sales amount generated by each customer.
select c.customer_id,c.customer_name,sum(p.price*o.quantity) as total_sales_amount
from customer_details c  inner join order_details o inner join product_details p
on c.customer_id=o.customer_id and p.product_id=o.product_id group by c.customer_id,c.customer_name;

#45. Find the customer who spent the highest total amount.
select c.customer_id,c.customer_name,sum(p.price*o.quantity) as total_sales_amount
from customer_details c  inner join order_details o inner join product_details p
on c.customer_id=o.customer_id and p.product_id=o.product_id group by c.customer_id,c.customer_name
order by total_sales_amount desc limit 1;

#46. Find the product that generated the highest total sales.
select p.product_id,p.product_name,sum(p.price*o.quantity) as total_sales_amount
from customer_details c  inner join order_details o inner join product_details p
on c.customer_id=o.customer_id and p.product_id=o.product_id group by p.product_id,p.product_name
order by total_sales_amount desc limit 1;

#47. Find the average order value.
select avg(p.price*o.quantity)
from order_details o inner join product_details p
on p.product_id=o.product_id ;

#48. Find customers who have placed at least one order.
select distinct(c.customer_name)
from customer_details c inner join order_details o
on  c.customer_id=o.customer_id ;

#49. Find customers who have never placed an order.
select distinct(c.customer_name)
from customer_details c left join order_details o
on  c.customer_id=o.customer_id where o.order_id is Null;

#50. Find products that have never been ordered.
select p.product_name,p.product_id
from product_details p left join order_details o
on  p.product_id=o.product_id where o.order_id is null;

#51. Find the customer(s) who placed the highest number of orders.
select c.customer_name,count(o.order_id) no_of_order
from customer_details c  inner join order_details o 
on c.customer_id=o.customer_id group by c.customer_name,c.customer_id order by no_of_order desc limit 1;
